### PR TITLE
SP-301: Expand DP template content after experience with SSDC-DP-005

### PR DESCRIPTION
**Pull request by gpdf**
Includes more subsections and some boilerplate text.  Further changes were included after working with SSDC-DP-002.

### CODE REVIEW

**Comment by rpaladini0406** [comment]
@gpdf what is it meant here for "deployment secret" ?

**Review by rpaladini0406 — CHANGES_REQUESTED** [review]
@gpdf can we slighlty rename the following sections ? 

1) Production -> Data Product/s Generation
2) Release -> Data Product/s Release

**Comment by gpdf** [comment]
> @gpdf what is it meant here for "deployment secret" ?

It is an authorization token that the CI workflows for documents require in order to be allowed to write the resulting PDF and metadata to the document deployment site https://spherex-docs.ipac.caltech.edu .  It is stored in the IPAC-SW and SPHEREx GitHub organizations in a secure way, so that the token never appears in plaintext.  An individual repository, like https://github.com/SPHEREx/ssdc-dp-002 , must be given permission for its workflows to retrieve that secret.

**Review by rpaladini0406 — APPROVED** [review]
Looks good

**Pull request merged**
